[package]
name = "godot_wry"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = ["api-4-2"] }
raw-window-handle = "0.6.2"
# wry = { version = "0.54.1", features = ["transparent", "devtools", "drag-drop", "os-webview", "x11"] }
# Fork that fixes https://github.com/tauri-apps/wry/issues/1663
wry = { git = "https://github.com/Ughuuu/wry", branch = "try-to-fix-application-window-crash-popup-linux", features = ["transparent", "devtools", "drag-drop", "os-webview", "x11"] }
http = "1.1.0"
lazy_static = "1.5.0"
serde_json = "1.0"
[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18.1"
x11-dl = "2.21.0"
[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61.1", features = ["Win32", "Win32_UI", "Win32_UI_WindowsAndMessaging", "Win32_System_Registry", "Win32_System_Diagnostics_Etw"]}
[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"
